#### Keiko: Global Configuration ##################################################
#
#   Welcome here!
#
#   This file lets you configure, as its name supposes, global options, that
# affect Keiko in general (all its parts at the same time).
#
#   Useful stuff:
#
#     1. Keiko Wiki (a lot of useful information):
#        --> https://github.com/MeGysssTaa/keiko-plugin-inspector/wiki
#
#     2. Keiko Discord (for questions, discussion, and live support):
#        --> https://discord.gg/QWHzCXX
#
###################################################################################




# What locale (language) should Keiko display its messages in?
# https://github.com/MeGysssTaa/keiko-plugin-inspector/wiki/Locales
locale: en_US

# How often should Keiko check for its own updates? When a newer version
# of Keiko is out, you will automatically be notified about that.
# This value is measured in minutes (default: 120 minutes = check every 2 hours).
#
# Special options:
#
#     * set to 0 to disable periodic updates checking. Keiko will still
#       check for updates on startup (remember - updating is important!);
#
#     * set to -1 to disable updates checking completely. Keiko will
#       not check for updates at all (not recommended!).
updates_check_freq_mins: 120

# Should Keiko save all its output in own log files (.../plugins/Keiko/logs/)?
# This will allow you to perform deep analysis any time in case something happens.
# Debug data is also written in logs, even if "enable_debug" is set to "false".
make_logs: true

# Keiko automatically deletes log files that are older than the number of days
# specified below. If you don't want Keiko to manage its logs automatically,
# you can disable this feature by setting logs_lifespan_days to -1.
logs_lifespan_days: 7

# Show debug (detailed verbose) messages in console?
enable_debug: false

# What should Keiko do if it fails to analyse a JAR?
#
#     warn     - Just print a warning in console and keep inspecting other JARs.
#                NOTE: not recommended: this may let some potentially malicious plugins run.
#
#     shutdown - Print a warning in console and shut the server down.
failure_policy: shutdown

# When Keiko encounters a critical issue that could be harmful to your server
# (e.g. detects malware on server's early boot), it will do its best to shut
# your server down as soon as possible to avoid it being damaged. The most
# efficient way of shutting down is so-called "rage quit" - "pkill -9 <pid>".
#
# Do you allow Keiko to perform rage quits in special/extreme cases?
# If you will forbid it to, then Bukkit#shutdown() will be used instead,
# which is often pretty slow and still lets the installed plugins enable.
#
# NOTE #1: this feature may not work properly on some certain servers, since
#          process ID retrieval is difficult to implement for Java 8 properly.
#
# NOTE #2: this feature may cause Keiko to stop the server before logging any
#          information in server console, which may sometimes look like the
#          server is getting crashed for no reason. If you're experiencing
#          this kind of issue make sure to check Keiko logs, which are located
#          in '.../plugins/Keiko/logs/YYYY-MM-dd.log' files (log name = current date).
allow_keiko_rage_quit: true
